inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7

  DisplayCopNames: true
  Exclude:
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrivialAccessors:
  AllowPredicates: true
